# Session 8

Types of scaler (StandardScaler, MinMaxScaler) - Work with text : Encode texts (OneHot, LabeleEncoder)-Text Vectorizer (CountVectorize, TF-IDF) -
pre_processing on texts : Normalizer, Tokenizer, Stemming, Stopword remover (work with Parsivar (biult on nltk))-Recommender system

## Scalers

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
#StandardScaler min-->0 std--> 1
score1 = np.array([1,2.5,3,5]).reshape(-1,1)
score2 = np.array([12,17,9,20]).reshape(-1,1)
score3 = np.array([20,50,100,74]).reshape(-1,1)

scaler = StandardScaler()
score_new=scaler.fit_transform(score1)
score_new

#Inverse
scaler.inverse_transform(score_new)

array([[1. ],
       [2.5],
       [3. ],
       [5. ]])

In [3]:
#MinMax
scaler = MinMaxScaler(feature_range=(0,100)) #range you want
scaler.fit([[9],[20]]) #min and max of your list must be detrmined
scaler.transform(score2)

array([[ 27.27272727],
       [ 72.72727273],
       [  0.        ],
       [100.        ]])

In [4]:
#Inverse
scaler.inverse_transform([[90]])

array([[18.9]])

## Text Vectorize and Encoding

OneHotEncoder:     Gender → Male=1/Female=0 

LabelEncoder:      Gender → Male=1, Female=0 (single column)

CountVectorizer:   Text → word counts (bag of words)

All are encoders — just for different data types!

In [5]:
name = np.array(['mobile','speaker','mobile','headset','speaker'])

In [6]:
#LabelEncoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
encoder = LabelEncoder()
encoder.fit_transform(name)

array([1, 2, 1, 0, 2], dtype=int64)

In [7]:
#OneHot
encoder = OneHotEncoder()
result=encoder.fit_transform(name.reshape(-1,1))
print(result.toarray())
#Each name = one column
#Value = 1 if matches, 0 if not
#→ "Is this Ali? Yes/No"

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [8]:
#Countvectorize
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
name = np.array(['mobile mobile','speaker','mobile','headset','speaker'])
vectorize = CountVectorizer()
vectorize.fit_transform(name)

#take the encodes with vocab_
print(vectorize.vocabulary_)

#get the unique 
print(vectorize.get_feature_names_out())
vectorize.fit_transform(name).toarray()

{'mobile': 1, 'speaker': 2, 'headset': 0}
['headset' 'mobile' 'speaker']


array([[0, 2, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]], dtype=int64)

In [10]:
#onehot is for words - countvectorize for text
#Example in text
from sklearn.feature_extraction.text import CountVectorizer

docs = ['cat dog cat', 'dog bird']

vectorizer = CountVectorizer()
result = vectorizer.fit_transform(docs)

#          bird  cat  dog
# Doc 1:  [0,   2,   1]   ← 2 cats, 1 dog, 0 birds
# Doc 2:  [1,   0,   1]   ← 1 bird, 0 cats, 1 dog
result.toarray()


array([[0, 2, 1],
       [1, 0, 1]], dtype=int64)

In [11]:
vec2 = CountVectorizer()
vec2.fit_transform([docs[0]])

<1x2 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

CountVectorizer: "cat" appears 5 times → score = 5

TF-IDF:          "cat" appears 5 times, BUT "cat" appears in EVERY document
                  → score = LOW (common word = not important)

                 "python" appears 2 times, BUT only in 1 document
                  → score = HIGH (rare word = very important!)


                  TF-IDF = TF × IDF

TF (Term Frequency)        = How often word appears in THIS document
IDF (Inverse Document Freq) = How RARE the word is across ALL documents

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit_transform(name).toarray()
print(vectorize.get_feature_names_out())
vectorize.vocabulary_


['headset' 'mobile' 'speaker']


{'mobile': 1, 'speaker': 2, 'headset': 0}

In [13]:
docs = ['cat dog cat', 'dog bird']

vectorizer = TfidfVectorizer()
result = vectorizer.fit_transform(docs)

result.toarray()



array([[0.        , 0.94215562, 0.33517574],
       [0.81480247, 0.        , 0.57973867]])

In [14]:
CountVectorizer:                    TF-IDF:
          bird  cat  dog                  bird   cat   dog
Doc 1:  [  0,    2,   1 ]         Doc 1: [0.00, 0.88, 0.38]
Doc 2:  [  1,    0,   1 ]         Doc 2: [0.65, 0.00, 0.65]

CountVectorizer:                   TF-IDF:
  "cat"=2 (raw count)               "cat"=0.88 (high importance —
                                   appears twice but only in 1 doc!)
  "dog"=1 in both docs              "dog"=0.38 (low importance —
                                   appears in BOTH docs — common word)

SyntaxError: invalid character '—' (U+2014) (1620205545.py, line 7)

### Text Pre_processing 

In [15]:
from parsivar import Tokenizer, Normalizer
tokenizer = Tokenizer()
normalizer= Normalizer()

In [16]:
punctuation_list= "!@#$%^,،؟?،"
import re
def pre_processing(text):
    text = normalizer.normalize(text)
    text = re.sub(r'(.)\1{2,}', r'\1', text)
    text = "".join([char for char in text if char not in punctuation_list])
    tokens = tokenizer.tokenize_words(text)
    return text, tokens

pre_processing('سلاااام، چه طورییییی؟')

('سلام  چه طوری ', ['سلام', 'چه', 'طوری'])

In [17]:
#ُsentences tokenize
text = 'سلاااام، چه طورییییی؟.من که عالیم مرسییی'
tokens = tokenizer.tokenize_sentences(text)

text = ([char for char in text if char not in punctuation_list])
tokens
"".join(text)

'سلاااام چه طورییییی.من که عالیم مرسییی'

In [18]:
# Stemming
from parsivar import FindStems

stemmer = FindStems()
print(stemmer.convert_to_stem('کتابی'))
print(stemmer.convert_to_stem('کتاب های'))
print(stemmer.convert_to_stem('کتاب '))

print(stemmer.convert_to_stem('میخوانم'))
print(stemmer.convert_to_stem('میخوانیم'))



کتاب
کتاب
کتاب 
خواند&خوان
خواند&خوان


## Recmmonder System

In [19]:
# IMBD Data
df = pd.read_csv("imdb_top_1000.csv")
df

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN


In [20]:
import os
os.getcwd()

'D:\\ML Course\\Mesbah\\Session 8'

In [21]:
#Drop columns you do not need - has no effect on the RS
df.drop(columns=['Poster_Link','Released_Year','Certificate','Runtime','IMDB_Rating','Overview','Meta_score','No_of_Votes','Gross'])

,Series_Title,Genre,Director,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,Drama,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,"Crime, Drama",Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,"Action, Crime, Drama",Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,"Crime, Drama",Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,"Crime, Drama",Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler
...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,"Comedy, Drama, Romance",Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen
996,Giant,"Drama, Western",George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker
997,From Here to Eternity,"Drama, Romance, War",Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed
998,Lifeboat,"Drama, War",Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix


In [22]:
#make a new columns including all features
df["combine"] = df["Series_Title"] + " " + df['Genre'] + " " +df['Director'] + " "+ df['Star1'] + " " + df["Star2"] + " " + df['Star3'] + " "+ df["Star4"]  
df["combine"][0]

'The Shawshank Redemption Drama Frank Darabont Tim Robbins Morgan Freeman Bob Gunton William Sadler'

In [23]:
vectorize = CountVectorizer()
vectorize.fit(df['combine'])

vectorize.transform([df["combine"][0]])

<1x5817 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [24]:
#'The Shawshank Redemption Drama Frank Darabont Tim Robbins Morgan Freeman Bob Gunton William Sadler'

#problem Frank Darabont are consider as two person not one
df["combine"] = (df["Series_Title"].str.replace(" ", "_") + " " + 
                 df['Genre'].str.replace(",", "") + " " + 
                 df['Director'].str.replace(" ", "_") + " " +
                 df['Star1'].str.replace(" ", "_") + " " + 
                 df["Star2"].str.replace(" ", "_") + " " + 
                 df['Star3'].str.replace(" ", "_") + " " +
                 df["Star4"].str.replace(" ", "_"))

df["combine"][2]


'The_Dark_Knight Action Crime Drama Christopher_Nolan Christian_Bale Heath_Ledger Aaron_Eckhart Michael_Caine'

In [25]:
# All
vectorize = CountVectorizer()
vectorize.fit(df['combine'])
vectorize.transform(df["combine"])
print(vectorize.get_feature_names_out())
vectorize.vocabulary_

vectorize.transform(df["combine"])

['10_to_yuma' '12_angry_men' '12_years_a_slave' ...
 'ôkami_kodomo_no_ame_to_yuki' 'ömer_faruk_sorak' 'özge_özberk']


<1000x4490 sparse matrix of type '<class 'numpy.int64'>'
	with 8970 stored elements in Compressed Sparse Row format>

In [26]:
# how it wroks : first code each unique words then make a matrix and count them - each rwo is a document and each columns is a unique word
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# دو سند با کلمات مشترک
documents = [
    "apple banana apple orange",      # سند 1: سیب ۲ بار، موز ۱ بار، پرتقال ۱ بار
    "apple banana banana grape"       # سند 2: سیب ۱ بار، موز ۲ بار، انگور ۱ بار
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)
print(X.toarray())
print(vectorizer.vocabulary_)

[[2 1 0 1]
 [1 2 1 0]]
{'apple': 0, 'banana': 1, 'orange': 3, 'grape': 2}


In [27]:
# Similarity 
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
df = pd.read_csv("imdb_top_1000.csv")

df2=df.drop(columns=['Poster_Link','Released_Year','Certificate','Runtime','IMDB_Rating','Overview','Meta_score','No_of_Votes','Gross'])

df2["combine"] = (df["Series_Title"].str.replace(" ", "_") + " " + 
                 df['Genre'].str.replace(",", "") + " " + 
                 df['Director'].str.replace(" ", "_") + " " +
                 df['Star1'].str.replace(" ", "_") + " " + 
                 df["Star2"].str.replace(" ", "_") + " " + 
                 df['Star3'].str.replace(" ", "_") + " " +
                 df["Star4"].str.replace(" ", "_"))

vectorizer = CountVectorizer()
vectorizer.fit(df2['combine'])
result=vectorizer.transform(df2["combine"])

result.toarray()
vectorizer.get_feature_names_out()
print(vectorizer.vocabulary_)



{'the_shawshank_redemption': 4050, 'drama': 1152, 'frank_darabont': 1376, 'tim_robbins': 4115, 'morgan_freeman': 2912, 'bob_gunton': 631, 'william_sadler': 4368, 'the_godfather': 3966, 'crime': 929, 'francis_ford_coppola': 1370, 'marlon_brando': 2680, 'al_pacino': 248, 'james_caan': 1843, 'diane_keaton': 1084, 'the_dark_knight': 3946, 'action': 202, 'christopher_nolan': 872, 'christian_bale': 854, 'heath_ledger': 1638, 'aaron_eckhart': 189, 'michael_caine': 2790, '_part_ii': 118, 'robert_de_niro': 3409, 'robert_duvall': 3412, '12_angry_men': 1, 'sidney_lumet': 3715, 'henry_fonda': 1657, 'lee_j': 2435, '_cobb': 41, 'martin_balsam': 2684, 'john_fiedler': 2050, 'the_lord_of_the_rings': 4010, '_the_return_of_the_king': 152, 'adventure': 217, 'peter_jackson': 3189, 'elijah_wood': 1219, 'viggo_mortensen': 4264, 'ian_mckellen': 1739, 'orlando_bloom': 3084, 'pulp_fiction': 3255, 'quentin_tarantino': 3261, 'john_travolta': 2097, 'uma_thurman': 4224, 'samuel_l': 3585, '_jackson': 83, 'bruce_will

In [49]:
# User use its movie to find realted ones
#user_movie = input("Your movie:")
user_movie = 'The Godfather'
user_movie_index = df2[df2['Series_Title']==user_movie]
user_movie_index.index[0]

1

In [50]:
user_movie_index.index

Index([1], dtype='int64')

In [51]:
user_movie_vector = result.toarray()[user_movie_index.index[0]]
user_movie_vector.shape
user_movie_vector

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [52]:
user_movie_vector = result.toarray()[user_movie_index.index[0]]
user_movie_vector.tolist()

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,


In [53]:
vector = df2["combine"].iloc[user_movie_index.index[0]]
vectorizer.transform([vector]).toarray()


array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [54]:
nearest_neighbors = NearestNeighbors(n_neighbors=5, metric='cosine', algorithm='brute')
nearest_neighbors.fit(result)

,n_neighbors,5
,radius,1.0
,algorithm,'brute'
,leaf_size,30
,metric,'cosine'
,p,2
,metric_params,None
,n_jobs,None


In [55]:
#Explain cosine simi
a = [[0,0,1,1,0]]

b = [
     [0,0,1,1,0],
     [0,0,0,1,0],
     [0,1,1,1,0],
     [1,0,0,0,1]]
similiraties = cosine_similarity(a,b)
print(similiraties)

sorted_similarities = np.argsort(similiraties)
print(sorted_similarities.shape)

sorted_similarities = sorted_similarities[0][::-1]
sorted_similarities



[[1.         0.70710678 0.81649658 0.        ]]
(1, 4)


array([0, 2, 1, 3], dtype=int64)

In [61]:
#implement above on imbd
similiraties = cosine_similarity([user_movie_vector],result)
similiraties

sorted_similarities = np.argsort(similiraties)

sorted_similarities = sorted_similarities[0][::-1]
print(sorted_similarities)

similiraties.shape

[  1 974   3 108 484 416 823 849  74 809 164 523 305 447 485 670 398  71
 165 465 895 380 288 180 621 111 397  22 257 763 186 669 775 133 663 885
 356 888 649 893 232 896 218 112 774 639 901 782 791 384 802 103 630 622
 224 136 676 811 243 189 759 723 299 169 198 850 767 852 768 162 836 201
 153 696 695 147 693 687 332 680 335 163 505 611 577  55 953 954 450 958
 960 463  42 546 474 968 480  37  33 487  27 980 527  25 494 520 987  15
 989 519   6   4   2 512 949 222 597 921 922  87  86 424 603  77  79 931
 287 451 718 882 113 418 833 263 918 827 255  28 926 814 444 710 437 674
 308 442 345 132 584 938 664 261 762 375 441 241 123 607 533 653 438 939
 605 708 284 363 239 602 387 370 699 554 347 517 580 388 787 788 646 589
 619 383 274 742 285 682 280 572 439 302 336 254 636 491 432 443 720 765
 297 468   0 886 838 818  53 946 941 188  88  89  91 917 841 206 916  97
  98 122 883 881 154 880 141 200 868 981   9  20 652 128 360  17 121 364
 372 637 904 355 905  99 626  24  96 913  92 492 13

(1, 1000)

In [37]:
n_recommend=4
recommended_result = sorted_similarities[1:1+n_recommend]
print(recommended_result)
df["Series_Title"].iloc[recommended_result]


[974   3 108 484]


974    The Godfather: Part III
3       The Godfather: Part II
108                   Scarface
484               The Irishman
Name: Series_Title, dtype: object

In [40]:
# whole code
# Recommender system:

user_movie = input("Your movie: ")
user_movie_index = df2[df2['Series_Title'] == user_movie]
user_movie_index = user_movie_index.index[0]
user_movie_vector = result.toarray()[user_movie_index]
similarities = cosine_similarity([user_movie_vector], result)
similarities

sorted_similarities = np.argsort(similarities)
sorted_similarities = sorted_similarities[0][::-1]
sorted_similarities

n_recommend = 4
recommended_result = sorted_similarities[1:1+n_recommend]
df["Series_Title"].iloc[recommended_result]

Your movie:  The Dark Knight


155            Batman Begins
774             3:10 to Yuma
36              The Prestige
63     The Dark Knight Rises
Name: Series_Title, dtype: object

In [41]:
sorted_similarities


array([  2, 155, 774,  36,  63, 356, 852, 953,  42, 850, 888, 577, 901,
       782, 968, 832, 573, 217, 663, 201,  55, 696, 768, 896, 224, 931,
       893, 345, 710, 674, 918, 308, 718, 375, 241, 605, 602, 763, 397,
       465, 130, 773, 257, 108, 928, 621,  71, 111, 165,   1, 485, 180,
        22, 784, 528, 380, 895, 288,  87, 759, 512, 885, 505, 335, 222,
       103, 216, 340, 569, 416, 570, 198, 218, 642, 112, 172, 791, 823,
       147, 546, 384, 819, 169, 142, 153, 164, 802, 811, 809, 163, 527,
       140, 189, 519, 767, 186, 853, 394, 889, 847, 133, 778, 134, 520,
       136, 775, 181, 836, 849, 331,  86, 960, 669,  27, 625,  30,  31,
        33, 622, 676, 611, 958,  37, 463, 954, 951,  39, 949,  25, 630,
       974, 299, 450,   3,   4, 639,   6, 648, 989, 987, 985, 294, 983,
       655, 980, 979,  15, 944, 680, 687, 597, 709, 480, 484, 243, 909,
       487, 424, 326, 431, 162, 494,  77, 723,  79, 232, 496, 600, 160,
       930, 921, 922, 924, 695,  57, 436, 474, 603, 287, 351, 45

In [43]:
## with NN
from sklearn.neighbors import NearestNeighbors

# اول اسم فیلم را از کاربر بگیر
user_movie = input("Enter movie name: ")

# ساخت مدل NN
nn = NearestNeighbors(n_neighbors=5, metric='cosine', algorithm='brute')
nn.fit(result)

# پیدا کردن فیلم‌های مشابه
user_movie_index = df2[df2['Series_Title'] == user_movie].index[0]
user_movie_vector = result[user_movie_index]

distances, indices = nn.kneighbors(user_movie_vector)

# نتیجه (به جز خود فیلم)
recommended_result = indices[0][1:5]
print(df["Series_Title"].iloc[recommended_result])


Enter movie name:  The Dark Knight


155            Batman Begins
774             3:10 to Yuma
36              The Prestige
63     The Dark Knight Rises
Name: Series_Title, dtype: object


In [ ]:
indices

In [ ]:
distances